@startuml

title Autopartes ABC
skinparam linetype ortho

class Empresa {
-{static}margenComercial
-{static}mesesGarantia
incorporarAutoparte:cantidad:()
agregarAutoparte:()
aplicarImpuesto:a:()
consultarStock:()
agregarCliente:()
agregarAutoparte:()
calcularTotalVentasmes:()
calcularUnidadesVendidasProducto:()
calcularVentasCliente:()
calcularPrecioDeVenta:()
enGarantia:cliente:()
generarVenta:a:descuento:()
generarVenta:a:descuento:fecha:()
imprimir()
obtenerAutoparte:()
obtenerCliente:()
{static}new:descripcion:costo:()
{static}new()

}

class Autoparte {
-nroPieza
-stock
-cantVendidos 
-descripcion
-costo

consultarNroPieza()
agregarImpuesto:()
agregarStock:()
reducirStock:()
calcularPrecioDeVenta()
{static}new:descripcion:costo:()
imprimir()
}

class Cliente {
-dni
comprar:()
imprimir()
{static}new:()
}

class Carrito {
agregar:cant:()
imprimir()
{static}new()
}


class ItemVenta {
-autoparte
-cantidad
-precioVigente
-precioConImpuestos
calcularPrecios()
precioConImpuestos()
{static}new:cant:()
}

class Venta {
-totalNeto
-mesesGarantia
-porcentajeDescuento
-precioConImpuestos
-importeDescontado
-totalAbonado
obtenerPiezas()
imprimir()
{static}new:listaItems:desc:()
{static}new:listaItems:fecha:desc:()

}

class Impuesto{
{abstract}calcularImpuesto:()
}

class ImpuestoFijo{
-importe
calcularImpuesto:()
{static}new:()
}

class ImpuestoVariable{
-porcentaje
calcularImpuesto:()
{static}new:()
}

class ImpuestoEscalonado{
-tope1Inclusivo 
-tope1Inclusivo
-pcentaje1 
-pcentaje2
-pcentaje3
calcularImpuesto:()
modificarTope:tope2:()
modificarPctenaje:pcentaje2:pcentaje3:()
{static}new:tope2:pcentaje1:pcentaje2:pcentaje3:()
}



Empresa "1" o-- "0..*" Autoparte
Empresa "1" o-- "0..*" Cliente
Empresa "1" o-- "0..*" Venta
Venta "1" -- "1" Carrito
Venta "1" -- "1" Cliente
Carrito "1" o-- "0..*" ItemVenta
ItemVenta "0..*" -- "1" Autoparte
Impuesto  <|-- ImpuestoFijo
Impuesto  <|-- ImpuestoVariable
Impuesto  <|-- ImpuestoEscalonado
Impuesto  "0..*" --o "0..*" Autoparte



@enduml