@startuml

title Autopartes ABC
' skinparam linetype ortho

class Empresa {
-listaVentas
-listaClientes
-listaAutopartes
-{static}margenComercial
-{static}mesesGarantia
incorporarAutoparte:cantidad:()
agregarAutoparte:()
aplicarImpuesto:a:()
consultarStock:()
inicializar:()
{static}new:descripcion:costo:()
{static}margenComercial()
{static}margenComercial:()
{static}mesesGarantia()
{static}mesesGarantia:()
{static}new()

}

class Autoparte {
-nroPieza
-stock
-cantVendidos 
-descripcion
-costo
-listaImpuestos

consultarNroPieza()
agregarImpuesto:()
agregarStock:()
reducirStock:()
calcularPrecioDeVenta()
nroPieza()
vendidos()
inicializar:descripcion:costo:()
{static}new:descripcion:costo:()

}

class Cliente {
-dni
-listaVentas
inicializar:()
{static}new:()
}

class Carrito {
-items
agregar:cant:()
{static}new()
}


class ItemVenta {
-autoparte
-cantidad
-precioVigente
-precioConImpuestos
autoparte()
cantidad()
inicializar:cant:()
precioConImpuestos()
{static}new:cant:()
}

class Venta {
-cliente
-listaItems
-totalNeto
-mesesGarantia
-porcentajeDescuento
-precioConImpuestos
-importeDescontado
-fecha
-totalAbonado
inicializar:listaitems:desc:()
inicializar:listaitems:fecha:desc:()
monto()
fecha()
obtenerPiezas()
{static}new:listaItems:desc:()
{static}new:listaItems:fecha:desc:()

}

class Fecha {
-dia
-mes
-anio
diferenciaEnMeses():
inicializar:mes:anio:()
inicializarFechaHoy()
masRecienteQue:()
queAnio()
queDia()
queFecha()
queMes()
{static}new:mes:anio:()
{static}newFechaHoy()
}

class Impuesto{
{abstract}calcularImpuesto:()
}

class ImpuestoFijo{
-importe
calcularImpuesto:()
{static}new:()
}

class ImpuestoVariable{
-porcentaje
calcularImpuesto:()
{static}new:()
}

class ImpuestoEscalonado{
-tope1Inclusivo 
-tope1Inclusivo
-pcentaje1 
-pcentaje2
-pcentaje3
calcularImpuesto:()
{static}new:tope2:pcentaje1:pcentaje2:pcentaje3:()
}



Empresa "1" o-- "0..*" Autoparte
Empresa "1" o-- "0..*" Cliente
Empresa "1" o-- "0..*" Venta
Venta "1" -- "1" Carrito
Carrito "1" o-- "0..*" ItemVenta
ItemVenta "0..*" -- "1" Autoparte
Venta "0..*" -- "1"  Fecha
Impuesto  <|-- ImpuestoFijo
Impuesto  <|-- ImpuestoVariable
Impuesto  <|-- ImpuestoEscalonado
Impuesto  "0..*" --o "0..*" Autoparte



@enduml